// export const FETCH_DATA='FETCH_DATA';

export const PRODUCT_DATA="PRODUCT_DATA";
export const  SET_CATEGORIES="SET_CATEGORIES";
export const SEARCH_PRODUCT="SEARCH_PRODUCT";
export const SET_CATEGORIES_LIST="SET_CATEGORIES_LIST"
